spring:
  application:
    name: ordernotification
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true

logging:
  level:
    com.codedecode.ordernotification: DEBUG
    org.springframework.data.redis: DEBUG